# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOQb_P0NNXWmJbezVjdnpjGr4ow0fN4F
"""

import streamlit as st

def es_primo(numero):
    """
    Función para determinar si un número es primo.
    Un número primo es un número natural mayor que 1 que no tiene divisores positivos
    más que 1 y él mismo.
    """
    # Los números primos deben ser mayores que 1.
    if numero <= 1:
        return False

    # Se itera desde 2 hasta la raíz cuadrada del número.
    # Si se encuentra un divisor en este rango, el número no es primo.
    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            return False

    # Si no se encontraron divisores, el número es primo.
    return True

# --- Interfaz de la aplicación Streamlit ---

# Título de la aplicación que se mostrará en la web.
st.title("🔢 Verificador de Números Primos")

# Descripción o subtítulo.
st.write("Esta aplicación te ayuda a identificar si un número entero es primo o no.")

# Campo de entrada para que el usuario ingrese un número.
# `min_value=0` asegura que no se ingresen números negativos.
# `step=1` permite que el número se incremente de uno en uno.
numero_usuario = st.number_input("Ingresa un número entero:", min_value=0, step=1)

# Botón para ejecutar la verificación.
# El código dentro de este 'if' solo se ejecutará cuando el usuario haga clic en el botón.
if st.button("Verificar si es primo"):
    # Llama a la función 'es_primo' con el número del usuario.
    if es_primo(numero_usuario):
        # Si la función devuelve True, muestra un mensaje de éxito.
        st.success(f"¡El número {numero_usuario} SÍ es un número primo! 👍")
    else:
        # Si la función devuelve False, muestra un mensaje de error/advertencia.
        st.error(f"El número {numero_usuario} NO es un número primo. 👎")

# Añadimos un separador y una pequeña explicación teórica para el usuario.
st.markdown("---")
st.header("¿Qué es un número primo?")
st.info(
    "Un número primo es un número natural mayor que 1 que tiene únicamente dos "
    "divisores distintos: él mismo y el 1. Por ejemplo, 2, 3, 5, 7 y 11 son números primos."
)